// Copyright Legion. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace OWRPGGameplayTags
{
	// --- STATUSES (Survival) ---
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Draining_Stamina);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Draining_Mana);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Immunity_Draining);

	// --- EVENTS ---
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_OWRPG_FellOutOfWorld);

	// --- INPUT ---
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Interact);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_ToggleInventory);

	// --- CHEATS ---
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedMana);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedStamina);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);

	// ---------------------------------------------------------
	// --- ITEM SYSTEM (The New Logic) ---
	// ---------------------------------------------------------

	// CATEGORIES (For UI Sorting Only: "Which tab does this go in?")
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Weapon);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Armor);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Consumable);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Resource);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Category_Tool);

	// TRAITS (For Gameplay Logic: "What is this object?")
	// Usage
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Trait_Equippable);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Trait_Consumable); // Standard "Eat" action
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Trait_Throwable);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Trait_Burnable);   // Can be fuel

	// Material Composition (Crucial for interaction rules)
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Trait_Material_Metal);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Trait_Material_Wood);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Trait_Material_Stone);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Trait_Material_Organic);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Trait_Material_Magical); // e.g. Soul Gems

	// Damage Properties (If hit by this item)
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Trait_Damage_Blunt);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Trait_Damage_Slash);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Trait_Damage_Pierce);

	// --- ATTRIBUTES (For SetByCaller initialization) ---
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Strength);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Agility);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Intelligence);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Endurance);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Luck);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Willpower);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Defense);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_CriticalChance);

	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxStamina);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxMana);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxHunger);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_MaxThirst);

	// --- RACES / ORIGINS ---
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Race_Human);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Race_RockPerson);
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Race_Elf);

	// --- INVENTORY TAGS ---
	OWRPGRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(OWRPG_Inventory_Stack);
}